# This file was generated by GoReleaser. DO NOT EDIT.
cask "hangar" do
  name "hangar"
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/sjoeboo/hangar"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hangar"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    on_intel do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_darwin_amd64.tar.gz"
      sha256 "f6da2fa9b2d89fa3a7dbe15e883e4b0e4ceafa0535a1c09d54ff6f3e5630fdde"
    end
    on_arm do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_darwin_arm64.tar.gz"
      sha256 "25c788da6742d1246c7dac61a71dfe3fc7286176a8d4bca37789d56b1a3f8c24"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_linux_amd64.tar.gz"
      sha256 "206f52e8bcd6623aebc923e1267f9f07ccbb0e31bea54d4be7d7322aa1a156ef"
    end
    on_arm do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_linux_arm64.tar.gz"
      sha256 "7c0bb71b61417f4b066c3957fccc285d7e8b942452e2bc06048ada32dc60469d"
    end
  end

  zap trash: [
      "~/.hangar",
    ]

end
