# This file was generated by GoReleaser. DO NOT EDIT.
cask "hangar" do
  name "hangar"
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/sjoeboo/hangar"
  version "1.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hangar"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    on_intel do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_darwin_amd64.tar.gz"
      sha256 "11e8f7843415c7aa6b319c4f49b0929c3abaa9a72d6b2fe1b4145c0c5e99e01c"
    end
    on_arm do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_darwin_arm64.tar.gz"
      sha256 "ae36935931b80596fda062dff951f098435ef22edb727a4a3694546bcf4b1c88"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_linux_amd64.tar.gz"
      sha256 "7f7a513221291628f622dae734a1b6e9e35ed55534d49857f9b207cf0a6e36da"
    end
    on_arm do
      url "https://github.com/sjoeboo/hangar/releases/download/v#{version}/hangar_#{version}_linux_arm64.tar.gz"
      sha256 "479e1920b8700dc3ed88026a68bb3ad756a28c63e1c6d8660f6503f3c507af82"
    end
  end

  zap trash: [
      "~/.hangar",
    ]

end
