# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hangar < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/sjoeboo/hangar"
  version "1.0.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sjoeboo/hangar/releases/download/v1.0.1/hangar_1.0.1_darwin_amd64.tar.gz"
      sha256 "024df11ff2d9942622fd251263f9bbd298d6b6352e4e0af3bdbd947f0bffea17"

      define_method(:install) do
        bin.install "hangar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sjoeboo/hangar/releases/download/v1.0.1/hangar_1.0.1_darwin_arm64.tar.gz"
      sha256 "7bb48ad1ec64e020b39ec91f4c8d95511116969e0f3466a8bad717ee13fa108f"

      define_method(:install) do
        bin.install "hangar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sjoeboo/hangar/releases/download/v1.0.1/hangar_1.0.1_linux_amd64.tar.gz"
      sha256 "febc36aec9ce4f4798125e2b34868b791d3d4258ebc5a97e02cfdbf343dea49e"
      define_method(:install) do
        bin.install "hangar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sjoeboo/hangar/releases/download/v1.0.1/hangar_1.0.1_linux_arm64.tar.gz"
      sha256 "fb5cef45c29358aa188b8cd8e596b69f8e5dccb9bf378b0296212e1507a8edb4"
      define_method(:install) do
        bin.install "hangar"
      end
    end
  end

  test do
    system "#{bin}/hangar", "version"
  end
end
